<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.itson</groupId>
    <artifactId>UNO-Spin</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>agent</module>
        <module>assembler</module>
        <module>blackboard</module>
        <module>builder</module>
        <module>conexion</module>
        <module>conexion-interfaces</module>
        <module>control</module>
        <module>dominio</module>
        <module>dto</module>
        <module>mvc</module>
        <module>serializer</module>
        <module>servidor</module>
    </modules>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>2.21.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>assembler.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>