package enums;

public enum TipoAccion {
    JUGAR_CARTA,
    PEDIR_CARTA,
    GIRAR_RULETA,
    GRITAR_UNO,
    ABANDONAR_PARTIDA,
    RECONOCER_EVENTO,
    SELECCIONAR_COLOR,
    UNIRSE_PARTIDA,
    CONFIRMAR_INICIO
}
