package dto;

public enum TipoEventoRuletaDTO {
    CASI_UNO,
    DESCARTAR_POR_NUMERO,
    DESCARTAR_POR_COLOR,
    ROBAR_HASTA_AZUL,
    ROBAR_HASTA_ROJO,
    GUERRA,
    MOSTRAR_LA_MANO,
    INTERCAMBIO_DE_MANOS,
    PUNTUACION_MAS_BAJA
}
